# Generated by Django 3.1.2 on 2020-10-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title сайта')),
                ('description', models.TextField(help_text='до 180 символово', max_length=180, verbose_name='Description')),
                ('favicon', models.ImageField(upload_to=None, verbose_name='Иконка сайта')),
            ],
            options={
                'verbose_name': 'Заголовок, описание и иконка',
                'verbose_name_plural': 'Заголовок, описание и иконка',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название сати')),
                ('icon', models.TextField(help_text='https://fontawesome.com/icons?d=gallery', verbose_name='Иконка')),
                ('url', models.CharField(max_length=255, verbose_name='Ссылка на страницу в сети')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
    ]
