# Generated by Django 3.1.2 on 2020-10-24 18:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Инофрмация о проекте',
                'verbose_name_plural': 'Инофрмация о проекте',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_one', models.TextField(blank=True, verbose_name='Информация в первой колонке футера')),
                ('text_two', models.TextField(blank=True, verbose_name='Информация во второй колонке футера')),
                ('copyright', models.CharField(blank=True, max_length=255, verbose_name='Копирайт')),
            ],
            options={
                'verbose_name': 'Информация в футере сайта',
                'verbose_name_plural': 'Информация в футере сайта',
            },
        ),
        migrations.CreateModel(
            name='Politic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Политика конфиденциальности',
                'verbose_name_plural': 'Политика конфиденциальности',
            },
        ),
    ]
