# Generated by Django 3.1.2 on 2020-10-10 15:39

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название категории')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Порядок сортировки (необязательно)')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Заголовок')),
                ('kz_news', models.BooleanField(default=False, verbose_name='Новости Казахстана')),
                ('world_news', models.BooleanField(default=False, verbose_name='Международные новости')),
                ('main_news', models.BooleanField(default=False, verbose_name='Главная новость')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на изображение(parsed)')),
                ('image', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Изображение (необязательно)')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Новость')),
                ('views', models.BooleanField(default=0, verbose_name='Количество просмотров')),
                ('source', models.URLField(blank=True, null=True, verbose_name='Источник')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news', to='news.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('-pub_date',),
            },
        ),
    ]
