# Generated by Django 3.1.2 on 2020-10-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='parse_title',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Заголовок (parse)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, default=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Заголовок (parse)'), max_length=255, verbose_name='Заголовок'),
        ),
    ]
