# Generated by Django 3.1.2 on 2020-10-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201010_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_actual',
            field=models.BooleanField(default=False, verbose_name='Актуальное'),
        ),
    ]
