# Generated by Django 3.1.2 on 2020-10-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20201013_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
