# Generated by Django 3.1.2 on 2020-10-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20201013_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
    ]
