# Generated by Django 3.1.2 on 2020-10-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20201015_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сайт источник'),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(blank=True, null=True, verbose_name='Источник новости'),
        ),
    ]
