# Generated by Django 3.1.2 on 2020-10-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20201015_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='kz_news',
            field=models.BooleanField(default=False, verbose_name='Каз'),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_news',
            field=models.BooleanField(default=False, verbose_name='Главное'),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, max_length=555, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='post',
            name='world_news',
            field=models.BooleanField(default=False, verbose_name='Мир'),
        ),
    ]
