# Generated by Django 3.1.2 on 2020-10-23 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20201023_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='news.publication', verbose_name='Публикация'),
        ),
    ]
