# Generated by Django 3.1.2 on 2020-10-23 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_review_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.review', verbose_name='Ответ на комментарий'),
        ),
        migrations.AddField(
            model_name='review',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Опубликовать'),
        ),
    ]
