# Generated by Django 3.1.2 on 2020-10-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20201023_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='body',
        ),
    ]
