# Generated by Django 3.1.2 on 2020-10-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20201024_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='text',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='body',
            new_name='text',
        ),
    ]
