# Generated by Django 3.1.2 on 2020-10-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20201024_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_text', models.TextField(verbose_name='Уведомление')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Время и дата')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ('-pub_date',),
            },
        ),
    ]
