# Generated by Django 3.1.2 on 2020-11-01 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('pub_date',), 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
    ]
