# Generated by Django 3.1.2 on 2020-11-03 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_auto_20201101_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='author',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='category',
        ),
        migrations.RemoveField(
            model_name='review',
            name='publication',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
