# Generated by Django 3.1.2 on 2020-11-04 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_auto_20201103_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date', 'update_date'), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
