# Generated by Django 3.1.2 on 2020-11-04 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0020_auto_20201105_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_review', to=settings.AUTH_USER_MODEL),
        ),
    ]
